[servers]
# Nombre exacto del archivo en tu disco D:
granja_real_key = GRANJA_NUEVA_LAB4P0

[GRANJA_NUEVA_LAB4P0]
ip_local = 192.168.1.95
ip_netbird = 100.66.246.67
user = lab4p0
quartus_path = /home/lab4p0/altera_lite/25.1std/quartus/bin/quartus_pgm
base_project_path = /home/lab4p0/proyectos_fpga
log_file_path = /home/lab4p0/logs/fpga_log.txt
quartus_primepro_path = /home/lab4p0/.config/altera_pro/26.1/quartus/bin/quartus_pgm
primepro_project_path = /home/lab4p0/proyectos_fpga_Agilex
primepro_log_file_path = /home/lab4p0/logs_Agilex/Agilex_fpga_log.txt